routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Route::get('/', 'Frontend\FrontendController@index');
Route::get('/about-us', 'Frontend\FrontendController@aboutUs')->name('aboutUs');
Route::get('/contact-us', 'Frontend\FrontendController@contactUs')->name('contactUs');

Auth::routes();

Route::resource('/users', 'Backend\UserController')->middleware('auth');

Route::resource('/logos', 'Backend\LogoController')->middleware('auth');

Route::group(['prefix' => 'profile', 'middleware' => ['auth']], function(){
    Route::get('/', 'Backend\ProfileController@show')->name('profile');
    Route::get('/{user}/edit', 'Backend\ProfileController@edit')->name('profile.edit');
    Route::put('/{user}', 'Backend\ProfileController@update')->name('profile.update');
});

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function(){
    Route::get('/change-password', 'Auth\ChangePasswordController@index')->name('change.password');
    Route::post('/change-password', 'Auth\ChangePasswordController@update')->name('update.password');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'role','name', 'email', 'password', 'gender', 'address', 'mobile', 'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Backend/LogoController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Logo;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class LogoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.logo.index')->with('logos', Logo::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.logo.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->hasFile('image')){
            // creating a instance of the logo class
            $logo = new Logo();
            // assigning the creator id
            $logo->created_by = Auth::user()->id;

            // upload it
            $image = $request->image->store('upload/logos');
            // assign it
            $logo->image = $image;
            $logo->save();
        };

        return redirect(route('logos.index'))->with('success', 'Logo uploaded successfully');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Logo $logo)
    {
        return view('backend.logo.create')->with('logo', $logo);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Logo $logo)
    {
        // check if new image
        if($request->hasFile('image')){
            // assigning the updator id
            $logo->updated_by = Auth::user()->id;

            // upload it
            $image = $request->image->store('upload/logos');

            // delete old one
            Storage::delete($logo->image);

            $logo->update(['image' => $image]);

            return redirect(route('logos.index'))->with('success', 'Logo has been updated');
        };
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Logo $logo)
    {
        Storage::delete($logo->image);

        $logo->delete();

        return redirect()->back()->with('error', 'Logo has been Deleted');
    }
}

app/Http/Controllers/Backend/ProfileController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class ProfileController extends Controller
{

    public function show()
    {
        $id= Auth::user()->id;
        $user = User::findOrFail($id);
        return view('backend.user.profile')->with('user', $user);
    }

    public function edit(User $user)
    {
        return view('backend.user.profile-edit')->with('editData', $user);
    }

    public function update(Request $request, User $user)
    {
        $rules = [
            'name' => 'required',
            'email' => 'required|unique:users,email,'.$user->id,
        ];

        $this->validate($request, $rules);

        // check if new image
        if($request->hasFile('image')){
            // upload it
            $image = $request->image->store('upload/user_images');

            // delete old one
            Storage::delete($user->image);

            $user->update(['image' => $image]);
        };

        $user->update([
            'name' => $request->name,
            'email' => $request->email,
            'mobile' => $request->mobile,
            'address' => $request->address,
            'gender' => $request->gender,
        ]);

        return redirect(route('profile'))->with('success', 'Your profile has been updated');
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.user.index')->with('users', User::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            'role' => 'required',
            'name' => 'required',
            'email' => 'required|unique:users,email',
            'password' => 'required|min:6',
            'confirmPassword' => 'required_with:password|same:password'
        ];

        $this->validate($request, $rules);

        User::create([
            'role' => $request->role,
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),

        ]);

        return redirect(route('users.index'))->with('success', 'New User Added Successfuly');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('backend.user.create')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $rules = [
            'role' => 'required',
            'name' => 'required',
            'email' => 'unique:users,email,'.$user->id
        ];

        $this->validate($request, $rules);

        $user->update([
            'role' => $request->role,
            'name' => $request->name,
            'email' => $request->email,
        ]);

        return redirect(route('users.index'))->with('success', 'User Updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        Storage::delete($user->image);

        $user->delete();

        return redirect()->back()->with('danger', 'User has been Deleted');
    }
}

resources/views/backend/user/create.blade.php
@extends('backend.layouts.master')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Manage User</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                            <li class="breadcrumb-item">{{ isset($user) ? 'Edit User' : 'Add User'}}</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    <section class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h3>{{ isset($user) ? 'Edit User' : 'Add User' }}
                                    <a class="btn btn-success btn-sm float-right" href="{{ route('users.index') }}"><i class="fas fa-list"></i> User List</a>
                                </h3>
                            </div>
                            <div class="card-body">
                                <form action="{{ isset($user) ? route('users.update', $user->id) : route('users.store') }}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    @if(isset($user))
                                        @method('PUT')
                                    @endif
                                    <div class="form-row">
                                        <div class="form-group col-md-4">
                                            <label for="role">User Role</label>
                                            <select name="role" id="role" class="custom-select">
                                                    <option value="" selected>Select Role</option>
                                                @if(isset($user))
                                                    <option value="admin" @if($user->role === "admin") selected @endif>Admin</option>
                                                    <option value="user" @if($user->role === "user") selected @endif>User</option>
                                                @else
                                                    <option value="admin">Admin</option>
                                                    <option value="user">User</option>
                                                @endif

                                            </select>
                                            @error('role')
                                            <div class="text-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label for="name">Name</label>
                                            <input name="name" type="text" class="form-control" id="name" @if(isset($user)) @if($user) value="{{ $user->name }}" @endif  @endif>
                                            @error('name')
                                            <div class="text-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label for="email">Email</label>
                                            <input name="email" type="email" class="form-control" id="email" @if(isset($user)) @if($user) value="{{ $user->email }}" @endif  @endif>
                                            @error('email')
                                            <div class="text-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                        @if(isset($user))

                                            @else
                                            <div class="form-group col-md-4">
                                                <label for="password">Password</label>
                                                <input name="password" type="password" class="form-control" id="password">
                                                @error('password')
                                                <div class="text-danger">{{ $message }}</div>
                                                @enderror
                                            </div>
                                            <div class="form-group col-md-4">
                                                <label for="confirmPassword">Confirm Password</label>
                                                <input name="confirmPassword" type="password" class="form-control" id="confirmPassword">
                                                @error('confirmPassword')
                                                <div class="text-danger">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        @endif

                                        <div class="form-group col-md-6">
                                            <input type="submit" value=" {{ isset($user) ? 'Update' : 'Submit' }}" class="btn btn-primary">
                                        </div>
                                        </div>
                                </form>
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div>

@endsection

resources/views/backend/user/index.blade.php
@extends('backend.layouts.master')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Manage User</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('home') }}">Home</a></li>
                            <li class="breadcrumb-item">User</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                @if (session('success'))
                    <div class="alert alert-success">
                        {{ session('success') }}
                    </div>
                @endif
                    @if (session('error'))
                    <div class="alert alert-danger">
                        {{ session('error') }}
                    </div>
                @endif

                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    <section class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h3>User List
                                    <a class="btn btn-success btn-sm float-right" href="{{ route('users.create') }}"><i class="fas fa-plus-circle"></i> Add User</a>
                                </h3>
                            </div>
                            <div class="card-body">
                                <table id="example1" class="table table-bordered table-hover">
                                    <thead class="bg-dark">
                                        <tr>
                                            <th>ID</th>
                                            <th>Role</th>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($users as $user)
                                    <tr>
                                        <td>{{ $user->id }}</td>
                                        <td>{{ $user->role }}</td>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td class="d-flex justify-content-around"><a title="edit" class="btn btn-primary btn-sm" href="{{ route('users.edit', $user->id) }}"><i class="fas fa-user-edit"></i></a>
                                            <button title="delete" type="submit" onclick="handleDelete({{ $user->id }})" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#exampleModal"><i class="fas fa-trash"></i></button>
                                        </td>
                                    </tr>
                                    @endforeach
                                    </tbody>
                                </table>

                                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <form action="" method="POST" id="deleteUser">
                                            @csrf
                                            @method('DELETE')
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="deleteModalLabel">Delete User</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <p class="text-center font-weight-bold">Are you sure you want to delete this User?</p>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                    <button type="submit" class="btn btn-danger">Confirm</button>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                </div>
                        </div>
                    </section>
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div>

@endsection

@section('css')
    <!-- DataTables -->
    <link rel="stylesheet" href="{{ asset('backend') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="{{ asset('backend') }}/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
@endsection

@section('script')
    <!-- DataTables -->
    <script src="{{ asset('backend') }}/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="{{ asset('backend') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="{{ asset('backend') }}/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="{{ asset('backend') }}/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>

    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
            });
        });
    </script>

    <script>
        function handleDelete(id){
            var form = document.getElementById('deleteUser');
            form.action = '/users/' + id;
            $('#deleteModal').modal('show');
        }
    </script>


@endsection

resources/views/backend/user/profile-edit.blade.php
@extends('backend.layouts.master')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark">Manage Profile</h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="{{ route('users.index') }}">Home</a></li>
                            <li class="breadcrumb-item">Profile</li>
                        </ol>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <!-- Main row -->
                <div class="row">
                    <!-- Left col -->
                    <section class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <h3>Edit Profile
                                    <a class="btn btn-success btn-sm float-right" href="{{ route('profile') }}"><i class="fas fa-user"></i> Your Profile</a>
                                </h3>
                            </div>
                            <div class="card-body">
                                <form action="{{ route('profile.update', $editData->id ) }}" method="POST" enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-row">
                                        <div class="form-group col-md-4">
                                            <label for="name">Name</label>
                                            <input name="name" type="text" class="form-control" id="name" value="{{ $editData->name }}">
                                            @error('name')
                                            <div class="text-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label for="email">Email</label>
                                            <input name="email" type="email" class="form-control" id="email" value="{{ $editData->email }}">
                                            @error('email')
                                            <div class="text-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label for="mobile">Mobile</label>
                                            <input name="mobile" type="text" class="form-control" value="{{ $editData->mobile }}">
                                        </div>
                                        <div class="form-group col-md-4">
                                            <label for="address">Address</label>
                                            <input name="address" type="text" class="form-control" value="{{ $editData->address }}">
                                        </div>
                                    <div class="form-group col-md-4">
                                        <label for="gender">Gender</label>
                                        <select name="gender" id="gender" class="custom-select">
                                            <option value="" selected>Select Gender</option>
                                            <option value="male" @if($editData->gender === "male") selected @endif>Male</option>
                                            <option value="female" @if($editData->gender === "female") selected @endif>Female</option>
                                        </select>
                                    </div>
                                        <div class="form-group col-md-4">
                                            <label for="image">Image</label>
                                            <input type="file" name="image" class="form-control-file" id="image">
                                        </div>
                                        <div class="form-group col-md-2">
                                            <img id="showImage" src="{{ (!empty($editData->image)) ? asset('storage/'.$editData->image) : asset('storage/upload/default.png') }}" class="img-fluid" alt="Responsive image" style="max-height: 120px">
                                        </div>
                                        <div class="form-group col-md-6 pt-5">
                                            <input type="submit" value="update" class="btn btn-primary">
                                        </div>
                                    </div>
                                </form>
                                    </div>
                                </form>
                            </div>
                    </section>
                </div>
            </div>
        </section>
        <!-- /.content -->
    </div>

@endsection

@section('script')
    <script type="text/javascript">
        $(document).ready(function () {
            $('#image').change(function (e) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#showImage').attr('src', e.target.result);
                }
                reader.readAsDataURL(e.target.files['0']);
            });
        });
    </script>
@endsection